version: '3'

vars:
  DOCKER_COMPOSE_FILE: deploy/docker/docker-compose.yml

tasks:
  default:
    desc: Build and start all services
    deps:
      - start-all

  start-all:
    desc: Build (с кэшем) and start all services
    cmds:
      - task: build-all
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} up

  build-all:
    desc: Build all Docker images
    deps:
      - swagger
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} build

  run-all:
    desc: Start all services (docker-compose up)
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} up

  flush-all:
    desc: Stop services and remove volumes
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} down -v

  build:
    desc: Build Go binaries locally
    cmds:
      - go build ./...

  test:
    desc: Run tests
    cmds:
      - go test ./...

  send-messages:
    desc: Send messages to gateway
    cmds:
      - go run cmd/scripts/send-messages/main.go

  swagger:
    desc: Generate Swagger documentation for coordinator and gateway
    cmds:
      - swag init -g internal/coordinator/http/doc.go -o docs/swagger-coordinator --parseDependency --parseInternal --exclude internal/gateway
      - swag init -g internal/gateway/http/server.go -o docs/swagger-gateway --parseDependency --parseInternal --exclude internal/coordinator

  infra-up:
    desc: Start only infrastructure (nats, etcd)
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} up -d nats etcd

  logs:
    desc: Show logs from all services
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} logs -f
