// Package swagger_in_memory Code generated by swaggo/swag. DO NOT EDIT
package swagger_in_memory

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Проверка работоспособности хранилища",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/storageapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages": {
            "post": {
                "description": "Сохраняет новое сообщение в in-memory хранилище",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Сохранить сообщение",
                "parameters": [
                    {
                        "description": "Данные сообщения",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storageapi.StoreMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/storageapi.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/storageapi.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Сообщение уже существует",
                        "schema": {
                            "$ref": "#/definitions/storageapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/storageapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/count": {
            "get": {
                "description": "Возвращает общее количество сообщений в хранилище",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Количество сообщений",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storageapi.CountResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/storageapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/{id}": {
            "get": {
                "description": "Возвращает сообщение из хранилища по его идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Получить сообщение по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор сообщения",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storageapi.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "Сообщение не найдено",
                        "schema": {
                            "$ref": "#/definitions/storageapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/storageapi.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Хранилище не инициализировано",
                        "schema": {
                            "$ref": "#/definitions/storageapi.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "storageapi.CountResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                }
            }
        },
        "storageapi.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "storageapi.MessageResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "payload": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "routing_key": {
                    "type": "string"
                },
                "routing_settings": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "scheduled_at": {
                    "type": "string"
                }
            }
        },
        "storageapi.StoreMessageRequest": {
            "type": "object",
            "properties": {
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "payload": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "routing_key": {
                    "type": "string"
                },
                "routing_settings": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "scheduled_at": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Проверка состояния хранилища",
            "name": "Health"
        },
        {
            "description": "Операции с сообщениями",
            "name": "Messages"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Orbital In-Memory Storage API",
	Description:      "API для взаимодействия с in-memory хранилищем сообщений Orbital.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
